# Generated by Django 4.2.2 on 2023-06-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
    ]
